# Generated by Django 5.2 on 2025-04-25 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendedoras', '0011_alter_produto_maleta_alter_produto_tipos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('maleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vendedoras.maleta')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vendedoras.produtos')),
            ],
        ),
    ]
