# Generated by Django 5.2 on 2025-05-02 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendedoras', '0015_alter_representantes_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_venda', models.DateField(auto_now=True, verbose_name='Data de venda')),
                ('data_atualizada', models.DateField(auto_now_add=True, verbose_name='Atualização')),
                ('maleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vendedoras.maleta')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vendedoras.produto')),
            ],
        ),
    ]
