# Generated by Django 5.2 on 2025-04-25 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidade', '0001_initial'),
        ('vendedoras', '0011_alter_produto_maleta_alter_produto_tipos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vendedoras.produto'),
        ),
    ]
