# Generated by Django 5.2 on 2025-05-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidade', '0002_alter_venda_data_atualizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_venda',
            field=models.DateField(auto_now=True, verbose_name='Data de vend'),
        ),
    ]
