# Generated by Django 5.2 on 2025-05-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidade', '0003_alter_venda_data_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_atualizada',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_venda',
            field=models.DateField(auto_now_add=True, verbose_name='Atualizacao'),
        ),
    ]
