# Generated by Django 5.2 on 2025-05-04 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidade', '0004_alter_venda_data_atualizada_alter_venda_data_venda'),
        ('vendedoras', '0015_alter_representantes_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_atualizada',
            field=models.DateField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='maleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='vendedoras.maleta'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='vendedoras.produto'),
        ),
    ]
