# Generated by Django 5.2 on 2025-10-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidade', '0005_alter_venda_data_atualizada_alter_venda_maleta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_venda',
            field=models.DateField(auto_now_add=True, verbose_name='Venda'),
        ),
    ]
