# Generated by Django 5.2 on 2025-04-17 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pago', models.BooleanField()),
                ('n_pago', models.BooleanField()),
                ('data_compra', models.DateField(auto_now_add=True, verbose_name='Compra')),
                ('data_atualizacao', models.DateField(auto_now=True, verbose_name='Atulização')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinte', to='cliente.cliente', verbose_name='Cliente')),
            ],
        ),
    ]
