# Generated by Django 5.2 on 2025-04-18 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('vendedoras', '0007_maleta_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clinte', to='vendedoras.produto', verbose_name='Peças'),
            preserve_default=False,
        ),
    ]
