# Generated by Django 5.2 on 2025-04-18 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_vendas_produto'),
        ('vendedoras', '0008_produtos_remove_produto_produto_produto_tipos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinte', to='vendedoras.produtos', verbose_name='Peças'),
        ),
    ]
