# Generated by Django 5.2 on 2025-05-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_vendas_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='data_atualizacao',
            field=models.DateField(auto_now=True, verbose_name='Atulizado em '),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='data_compra',
            field=models.DateField(auto_now_add=True, verbose_name='Comprado em '),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='n_pago',
            field=models.BooleanField(verbose_name='Pendente'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='pago',
            field=models.BooleanField(verbose_name='Pago'),
        ),
    ]
