# Generated by Django 5.2 on 2025-04-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Representantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('rg', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=20)),
                ('telefone_2', models.CharField(blank=True, max_length=20, null=True)),
                ('instagram', models.CharField(max_length=30)),
                ('ativo', models.BooleanField(verbose_name='ATIVO')),
                ('inativo', models.BooleanField(verbose_name='INATIVO')),
            ],
        ),
    ]
