# Generated by Django 5.2 on 2025-04-13 00:28

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('vendedoras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='representantes',
            name='data_criacao',
            field=models.DateField(auto_now_add=True, default='2025-04-12', verbose_name='Data do cadastro'),
            preserve_default=False,
        ),
    ]
