# Generated by Django 5.2 on 2025-04-13 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedoras', '0002_representantes_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representantes',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='ATIVO'),
        ),
    ]
