# Generated by Django 5.2 on 2025-04-16 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendedoras', '0003_alter_representantes_ativo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='representantes',
            options={'verbose_name': 'Consultora'},
        ),
    ]
