# Generated by Django 5.2 on 2025-04-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedoras', '0004_alter_representantes_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='representantes',
            name='bairro',
            field=models.CharField(default='teste', max_length=20),
        ),
        migrations.AddField(
            model_name='representantes',
            name='cep',
            field=models.CharField(default='teste', max_length=20),
        ),
        migrations.AddField(
            model_name='representantes',
            name='cidade',
            field=models.CharField(default='teste', max_length=20),
        ),
        migrations.AddField(
            model_name='representantes',
            name='numero',
            field=models.IntegerField(default=20, max_length=5),
        ),
        migrations.AddField(
            model_name='representantes',
            name='rua',
            field=models.CharField(default='teste', max_length=50),
        ),
    ]
