# Generated by Django 5.2 on 2025-04-18 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedoras', '0006_alter_representantes_bairro_alter_representantes_cep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Maleta')),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('consultora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendedoras.representantes', verbose_name='Consultora')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(choices=[('ANEL', 'Anel'), ('BRINCO', 'Brinco'), ('PULSEIRA', 'Pulseira'), ('CONJUNTO', 'Conjunto'), ('TORNOZELEIRA', 'Tornozeleira'), ('CORRENTE', 'Corrente')], max_length=20, verbose_name='Peças')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('maleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='vendedoras.maleta')),
            ],
        ),
    ]
