# Generated by Django 5.2 on 2025-04-18 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedoras', '0007_maleta_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Peças')),
            ],
        ),
        migrations.RemoveField(
            model_name='produto',
            name='produto',
        ),
        migrations.AddField(
            model_name='produto',
            name='tipos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='vendedoras.produtos'),
            preserve_default=False,
        ),
    ]
