# Generated by Django 5.2 on 2025-04-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedoras', '0008_produtos_remove_produto_produto_produto_tipos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maleta',
            options={'verbose_name': 'Mostruario'},
        ),
        migrations.AddField(
            model_name='maleta',
            name='atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='maleta',
            name='data_criacao',
            field=models.DateField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='maleta',
            name='nome',
            field=models.CharField(max_length=50, unique=True, verbose_name='Mostruario'),
        ),
    ]
