# Generated by Django 5.2 on 2025-04-22 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedoras', '0009_alter_maleta_options_maleta_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maleta',
            name='data_criacao',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Saida'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='maleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtox', to='vendedoras.maleta'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtox', to='vendedoras.produtos'),
        ),
    ]
