# Generated by Django 5.2 on 2025-04-25 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedoras', '0010_alter_maleta_data_criacao_alter_produto_maleta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='maleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='vendedoras.maleta'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='vendedoras.produtos'),
        ),
    ]
