# Generated by Django 5.2 on 2025-05-01 02:48

import vendedoras.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedoras', '0011_alter_produto_maleta_alter_produto_tipos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representantes',
            name='cpf',
            field=models.CharField(max_length=14, validators=[vendedoras.validators.validar_cpf]),
        ),
    ]
