# Generated by Django 5.2 on 2025-05-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedoras', '0012_alter_representantes_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representantes',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
    ]
