# Generated by Django 5.2 on 2025-05-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedoras', '0013_alter_representantes_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='representantes',
            name='email',
            field=models.EmailField(default='caio@gmail.com', max_length=254, unique=True),
        ),
    ]
