# Generated by Django 5.2 on 2025-05-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedoras', '0014_representantes_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representantes',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
